# Generated by Django 3.0.2 on 2020-01-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatergorieStructure',
            fields=[
                ('idcatergorie_structure', models.AutoField(db_column='idCATERGORIE_STRUCTURE', primary_key=True, serialize=False)),
                ('type_struct', models.CharField(blank=True, db_column='TYPE_STRUCT', max_length=45, null=True)),
            ],
            options={
                'db_table': 'CATERGORIE_STRUCTURE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(db_column='idCLIENT', primary_key=True, serialize=False)),
                ('nom_client', models.CharField(blank=True, db_column='NOM_CLIENT', max_length=45, null=True)),
                ('prenom_client', models.CharField(blank=True, db_column='PRENOM_CLIENT', max_length=45, null=True)),
                ('date_de_naissance_client', models.CharField(db_column='DATE_DE_NAISSANCE_CLIENT', max_length=45)),
                ('adresse_client', models.CharField(blank=True, db_column='ADRESSE_CLIENT', max_length=45, null=True)),
                ('email', models.CharField(db_column='EMAIL', max_length=45)),
                ('numero_telephone', models.IntegerField(db_column='NUMERO_TELEPHONE')),
                ('mot_de_passe_client', models.CharField(db_column='MOT_DE_PASSE_CLIENT', max_length=45)),
            ],
            options={
                'db_table': 'CLIENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('idrdv', models.AutoField(db_column='idRDV', primary_key=True, serialize=False)),
                ('date_rdv', models.DateTimeField(db_column='DATE_RDV')),
                ('heure_rdv', models.DateTimeField(db_column='HEURE_RDV')),
            ],
            options={
                'db_table': 'RDV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idservice', models.AutoField(db_column='idSERVICE', primary_key=True, serialize=False)),
                ('nom_service', models.CharField(blank=True, db_column='NOM_SERVICE', max_length=45, null=True)),
                ('duree_service', models.CharField(blank=True, db_column='DUREE_SERVICE', max_length=45, null=True)),
            ],
            options={
                'db_table': 'SERVICE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('idstaff', models.AutoField(db_column='idSTAFF', primary_key=True, serialize=False)),
                ('nom_staff', models.CharField(blank=True, db_column='NOM_STAFF', max_length=45, null=True)),
                ('prenom_staff', models.CharField(blank=True, db_column='PRENOM_STAFF', max_length=45, null=True)),
            ],
            options={
                'db_table': 'STAFF',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('idstructure', models.AutoField(db_column='idSTRUCTURE', primary_key=True, serialize=False)),
                ('nom_struct', models.CharField(blank=True, db_column='NOM_STRUCT', max_length=45, null=True)),
                ('adresse_struct', models.CharField(blank=True, db_column='ADRESSE_STRUCT', max_length=45, null=True)),
            ],
            options={
                'db_table': 'STRUCTURE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('iduser', models.AutoField(db_column='idUSER', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='NOM', max_length=45, null=True)),
                ('prenom', models.CharField(blank=True, db_column='PRENOM', max_length=45, null=True)),
                ('date_de_naissance', models.DateField(db_column='DATE_DE_NAISSANCE')),
                ('adresse', models.CharField(blank=True, db_column='ADRESSE', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=45, null=True)),
                ('numero_telephone', models.IntegerField(db_column='NUMERO_TELEPHONE')),
                ('mot_de_passe', models.CharField(blank=True, db_column='MOT_DE_PASSE', max_length=45, null=True)),
                ('code_postal', models.IntegerField(db_column='CODE_POSTAL')),
            ],
            options={
                'db_table': 'USERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demander',
            fields=[
                ('service_idservice', models.OneToOneField(db_column='SERVICE_idSERVICE', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bookili.Service')),
            ],
            options={
                'db_table': 'DEMANDER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servir',
            fields=[
                ('service_idservice', models.OneToOneField(db_column='SERVICE_idSERVICE', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bookili.Service')),
            ],
            options={
                'db_table': 'SERVIR',
                'managed': False,
            },
        ),
    ]
