# Generated by Django 3.0.2 on 2020-01-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookili', '0002_auto_20200120_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duree_service',
            field=models.TimeField(blank=True, db_column='DUREE_SERVICE', null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='code_postal',
            field=models.SmallIntegerField(blank=True, db_column='CODE_POSTAL', null=True),
        ),
    ]
